'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pak2GoReference
    Public Property Id As Integer
    Public Property RateId As Nullable(Of Integer)
    Public Property ReferenceNumber As String
    Public Property TrackNumber As String
    Public Property ShipmentId As Nullable(Of Integer)
    Public Property CreatedOn As Date
    Public Property ModifiedOn As Nullable(Of Date)

End Class
