'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProveedorReconciliaciones
    Public Property ID As Integer
    Public Property Proveedor As String
    Public Property guia_proveedor As String
    Public Property guia_draft As Nullable(Of Integer)
    Public Property costo As Nullable(Of Decimal)
    Public Property peso As Nullable(Of Decimal)
    Public Property no_cajas As Nullable(Of Integer)

End Class
